# Generated by Django 4.2.11 on 2024-05-13 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("freelancers", "0001_initial"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewaboutclient",
            name="from_freelancer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_reviews",
                to="freelancers.freelancerprofile",
            ),
        ),
        migrations.AddField(
            model_name="reviewaboutclient",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_reviews",
                to="clients.job",
            ),
        ),
        migrations.AddField(
            model_name="reviewaboutclient",
            name="to_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_reviews",
                to="clients.clientprofile",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="client_profile_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="clients.clientprofile",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="skill",
            field=models.ManyToManyField(related_name="jobs", to="core.skill"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
