# Generated by Django 4.2.11 on 2024-05-14 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelancers", "0001_initial"),
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewaboutclient",
            name="from_freelancer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_reviews",
                to="freelancers.freelancerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="reviewaboutclient",
            name="to_client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_reviews",
                to="clients.clientprofile",
            ),
        ),
    ]
