

services:
  backend:
    build: ./
    container_name: fp_container
    working_dir: /freelancer_platform
    ports:
      - "8010:8000"
    command:
      - ./commands/start_server_dev.sh
    volumes:
      - ./src:/freelancer_platform/src
      - ./commands:/freelancer_platform/commands
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15.7
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env



volumes:
  pg_data: { }