services:
  backend:
    build: ./
    container_name: fp_container
    working_dir: /freelancer_platform
    ports:
      - "8010:8000"
    command:
      - ./commands/start_server_dev.sh
    volumes:
      - ./src:/freelancer_platform/src
      - ./commands:/freelancer_platform/commands
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:15.7
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5000:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres


  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

volumes:
  pg_data: { }
  pgadmin_data: { }
  mongo_data: { }
