services:
  backend:
    build: ./
    container_name: fp_container
    working_dir: /freelancer_platform
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    command:
      - ./commands/start_server_${MODE}.sh
    volumes:
      - ./src:/freelancer_platform/src
      - ./commands:/freelancer_platform/commands
      - static_content:/freelancer_platform/src/static
      - media_content:/freelancer_platform/src/media
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15.7
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5000:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres


  #  mongodb:
  #    image: mongo:3-stretch
  #    container_name: mongo_db_container
  #    ports:
  #      - 27017:27017
  #    command: [ "--smallfiles" ]
  #    volumes:
  #      - mongo_data:/data/db
  #    env_file:
  #      - .env
  #    restart: on-failure
  #
  #  mongoadmin:
  #    image: mongo-express
  #    restart: on-failure
  #    container_name: mogno_admin_container
  #    ports:
  #      - 8091:8081
  #    env_file:
  #      - .env
  #    links:
  #      - mongodb
  #    depends_on:
  #      - mongodb

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/freelancer_platform/src/static
      - media_content:/freelancer_platform/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - backend

  redis:
    image: redis
    env_file:
      - .env
    depends_on:
      - backend

  celery:
    build: ./
    container_name: celery_container
    command: ./commands/start_celery.sh
    restart: on-failure
    volumes:
      - ./src:/freelancer_platform
      - ./commands:/freelancer_platform/commands
    env_file:
      - .env
    depends_on:
      - redis
      - backend
    ports:
      - 5556:5555

  celerybeat:
    build: ./
    container_name: celerybeat-container
    command:
      - ./commands/start_celerybeat.sh
    restart: on-failure
    volumes:
      - ./src:/freelancer_platform
      - ./commands:/freelancer_platform/commands
    env_file:
      - .env
    depends_on:
      - redis
      - backend


  #  redisadmin:
  #    image: redislabs/redisinsight
  #    container_name: redisadmin
  #    restart: on-failure
  #    ports:
  #      - 8001:8001
  #    env_file: .env

  redisadminold:
    image: rediscommander/redis-commander:latest
    container_name: redisadminold
    hostname: redisadminold
    restart: always
    ports:
      - 8092:8081
    env_file:
      - .env




volumes:
  pg_data: { }
  pgadmin_data: { }
  #  mongo_data: { }
  static_content: { }
  media_content: { }

