# Generated by Django 4.2.11 on 2024-05-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Freelancer"), (1, "Client")],
                default=0,
                verbose_name="user type",
            ),
        ),
    ]
