server {
    listen 80 default_server;
    listen 443 default_server;

    server_name ec2-3-16-30-55.us-east-2.compute.amazonaws.com;

    location /static/ {
        alias /freelancer_platform/src/static/;
    }

    location /media/ {
        alias /freelancer_platform/src/media/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_pass http://backend:8010;
    }

}