# Generated by Django 4.2.11 on 2024-05-19 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("freelancers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancerprofile",
            name="user",
            field=models.OneToOneField(
                default="images/default.jpg",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freelancer_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
