# Generated by Django 4.2.11 on 2024-05-14 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_reviewaboutclient_from_freelancer_and_more"),
        ("freelancers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewaboutfreelancer",
            name="from_client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_reviews",
                to="clients.clientprofile",
            ),
        ),
        migrations.AlterField(
            model_name="reviewaboutfreelancer",
            name="to_freelancer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_reviews",
                to="freelancers.freelancerprofile",
            ),
        ),
    ]
