# Generated by Django 4.2.11 on 2024-05-23 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import freelancers.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("freelancers", "0002_alter_freelancerprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancerprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="images/default.jpg",
                null=True,
                upload_to="images/freelancer_profile_photo/",
                validators=[freelancers.utils.validators.validate_file_size],
                verbose_name="photo",
            ),
        ),
        migrations.AlterField(
            model_name="freelancerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freelancer_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
