# Generated by Django 4.2.11 on 2024-05-16 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("freelancers", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankinginformation",
            name="freelancer_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freelancer_banking_information",
                to="freelancers.freelancerprofile",
            ),
        ),
    ]
