# Generated by Django 4.2.11 on 2024-05-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="title",
            field=models.CharField(max_length=150, unique=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
