name: Freelance_platform CI process

on:
  push:
  pull_request:

env:
  DJANGO_SETTINGS_MODULE: config.settings.dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11.3"]

    services:
      postgres:
        image: postgres:15.7
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }} and pipenv
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies with pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Check migrations
        run: |
          pipenv run python src/manage.py makemigrations
          pipenv run python src/manage.py migrate
          pipenv run python src/manage.py check
      - name: Run tests
        run: |
          pipenv run python src/manage.py test & pipenv run flake8
