name: Freelance_platform CI process

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }} and pipenv
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies with pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Check migrations
        run: |
          pipenv run python src/manage.py makemigrations
          pipenv run python src/manage.py migrate
          pipenv run python src/manage.py check
      - name: Run tests
        run: |
          pipenv run python src/manage.py test & run flake8
